name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install React dependencies
        run: |
          cd front-end
          yarn install

      - name: Run React tests
        run: |
          cd front-end
          yarn test

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Flask dependencies
        run: |
          cd back-end
          pip install -r requirements.txt

      - name: Run Flask tests
        run: |
          cd back-end
          pytest

      - name: Deploy if tests pass
        if: success()
        run: |
          cat .github/workflows/deploy.yaml
