services:
  frontend:
    image: leetun2k2/chess_frontend:latest
    ports:
      - 10040:80
    depends_on:
      - backend
    networks:
      - frontend_backend
      - frontend_stockfish
      - frontend_pikafish

  backend:
    image: leetun2k2/chess_backend:latest
    volumes:
      - ./uploads:/app/uploads
    environment:
      NEW_RELIC_LICENSE_KEY: 3b17d5c55b244bdd5433f5c852d84f13FFFFNRAL
      NEW_RELIC_APP_NAME: "Python Application"
    stdin_open: true
    tty: true
    restart: "no"
    container_name: chess_backend
    depends_on:
      - mongodb
    networks:
      - frontend_backend
      - backend_mongodb

  stockfish: 
    image: leetun2k2/stockfish:latest
    networks:
      - frontend_stockfish
  
  pikafish: 
    image: leetun2k2/pikafish:latest
    networks:
      - frontend_pikafish

  mongodb:
    image: mongo:latest
    networks:
      - backend_mongodb

networks:
  frontend_backend:
    driver: bridge
  backend_mongodb:
    driver: bridge
  frontend_stockfish:
    driver: bridge
  frontend_pikafish:
    driver: bridge
