services:
  frontend:
    image: chess/frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - frontend_backend

  backend:
    image: chess/backend
    depends_on:
      - mongodb
    networks:
      - frontend_backend
      - backend_mongodb

  mongodb:
    image: mongo:latest
    networks:
      - backend_mongodb

networks:
  frontend_backend:
    driver: bridge
  backend_mongodb:
    driver: bridge
