export const client_menu = [
    { id: 1, title: 'Home', link: '/' },
    { id: 2, title: 'Blogs', link: '/blogs' },
    { id: 3, title: 'Achievement', link: '/achievements' },
    { id: 4, title: 'Play vs Online', link: '/play/online' },
    { id: 5, title: 'Play vs Friend', link: '/play/friend' },
    { id: 6, title: 'Play vs Computer', link: '/play/computer' },
    { id: 7, title: 'Arena', link: '/arena' },
    { id: 8, title: 'Videos', link: '/videos' },
    { id: 9, title: 'Books', link: '/books' },
    { id: 10, title: 'TV', link: '/tv' },
    { id: 11, title: 'Profile', link: '/profile' },
    { id: 12, title: 'Settings', link: '/settings' },
    { id: 13, title: 'Log out', link: '/logout' },
]