name: Deploy to Amazon EC2

on:
  push:
    branches: ["production"]

env:
  AWS_REGION: ap-southeast-2
  EC2_IP_ADDRESS: ec2-3-27-9-1.ap-southeast-2.compute.amazonaws.com
  FE_IMAGE: leetun2k2/chess_frontend:latest
  BE_IMAGE: leetun2k2/chess_backend:latest
  STOCKFISH_IMAGE: leetun2k2/stockfish:latest
  PIKAFISH_IMAGE: leetun2k2/pikafish:latest

jobs:
  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.pem
          chmod 600 private.pem

      - name: Login to Docker Hub
        run: docker login --username ${{secrets.DOCKER_LOGIN_USERNAME}} --password ${{secrets.DOCKER_LOGIN_PASSWORD}}

      - name: Build and push front-end image
        run: |
          cd front-end
          docker build -f .docker/Dockerfile -t ${{env.FE_IMAGE}} .
          docker push ${{env.FE_IMAGE}}
      
      - name: Build and push back-end image
        run: |
          cd back-end
          docker build -f .docker/Dockerfile -t ${{env.BE_IMAGE}} .
          docker push ${{env.BE_IMAGE}}

      - name: Build and push stockfish image
        run: |
          cd stockfish
          docker build -f .docker/Dockerfile -t ${{env.STOCKFISH_IMAGE}} .
          docker push ${{env.STOCKFISH_IMAGE}}

      - name: Build and push pikafish image
        run: |
          cd pikafish
          docker build -f .docker/Dockerfile -t ${{env.PIKAFISH_IMAGE}} .
          docker push ${{env.PIKAFISH_IMAGE}}
          
      - name: EC2 stop and remove containers
        run: |
          ssh -o StrictHostKeyChecking=no -o "UserKnownHostsFile=/dev/null" -i private.pem ec2-user@${{env.EC2_IP_ADDRESS}} '
            cd chess
            docker-compose -f ./.docker/docker-compose.yaml down
          '

      - name: EC2 clear image
        run: |
          ssh -o StrictHostKeyChecking=no -o "UserKnownHostsFile=/dev/null" -i private.pem ec2-user@${{env.EC2_IP_ADDRESS}} '
            cd chess
            docker rm -vf $(docker ps -aq)
            docker rmi -f $(docker images -aq)
          '

      - name: EC2 pull images
        run: |
          ssh -o StrictHostKeyChecking=no -o "UserKnownHostsFile=/dev/null" -i private.pem ec2-user@${{env.EC2_IP_ADDRESS}} '
            docker pull ${{env.FE_IMAGE}}
            docker pull ${{env.BE_IMAGE}}  
            docker pull ${{env.STOCKFISH_IMAGE}}  
            docker pull ${{env.PIKAFISH_IMAGE}}  
          '

      - name: EC2 start containers
        run: |
          ssh -o StrictHostKeyChecking=no -o "UserKnownHostsFile=/dev/null" -i private.pem ec2-user@${{env.EC2_IP_ADDRESS}} '
            cd chess
            docker-compose -f ./.docker/docker-compose.yaml up -d
          '