name: Deploy to Amazon EC2

on:
  push:
    branches: ["production"]

env:
  AWS_REGION: ap-southeast-2
  EC2_IP_ADDRESS: "3.27.242.207"
  ECR_REPOSITORY: chess
  ECR_REGISTRY: 952043753825.dkr.ecr.ap-southeast-2.amazonaws.com
  FE_IMAGE: chess/frontend
  BE_IMAGE: chess/backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.pem
          chmod 600 private.pem

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        run: docker login -u AWS -p $(aws ecr get-login-password --region ${{env.AWS_REGION}}) ${{env.ECR_REGISTRY}}

      - name: Build and push front-end image
        run: |
          cd front-end
          docker build -f .docker/Dockerfile -t ${{env.FE_IMAGE}}:${{env.IMAGE_TAG}} .
          docker push ${{env.ECR_REPOSITORY}}/${{env.FE_IMAGE}}:${{env.IMAGE_TAG}}

      - name: Build and push back-end image
        run: |
          cd back-end
          docker build -f .docker/Dockerfile -t ${{env.BE_IMAGE}}:${{env.IMAGE_TAG}} .
          docker push ${{env.ECR_REPOSITORY}}/${{env.BE_IMAGE}}:${{env.IMAGE_TAG}}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.EC2_IP_ADDRESS}}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Pull images on EC2 instance
        run: |
          cd chess
          docker-compose -f .docker/docker-compose.yml pull

      - name: Stop and remove containers on EC2 instance
        run: |
          cd chess
          docker-compose -f .docker/docker-compose.yml down

      - name: Start containers on EC2 instance
        run: |
          cd chess
          docker-compose -f .docker/docker-compose.yml up -d
