name: SSH into Remote Host

on:
  push:
    branches:
      - test

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        

      - name: Install expect and ssh-client
        run: sudo apt-get install -y expect openssh-client

      - name: Run SSH Script
        run: |
          expect -c '
            set host "103.130.211.150"
            set user "hcmute"
            set password "hcmute@fit"

            spawn ssh -o StrictHostKeyChecking=no -p 10038 $user@$host
            expect {
              "assword:" {
                send "$password\r"
                exp_continue
              }
              "Permission denied" {
                exit 1
              }
              "Welcome" {
                send "cd project/20110746_20110643\r"
                send "./cli.sh\r"
                expect {
                  "Deploy ute-chess-club project completely" {
                    interact
                  }
                }
                timeout {
                  send_user "Timeout.\n"
                  exit 1
                }
              }
            }
          '
