name: SSH into Remote Host

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install expect and ssh-client
        run: sudo apt-get install -y expect openssh-client

      - name: Run SSH Script
        run: |
          expect -c '
            spawn ssh hcmute@103.130.211.150 -p 10038
            expect "password:"
            send "$password\r"
            interact
          '
